services:
  - type: web
    name: btc-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn inference:app --host 0.0.0.0 --port 10000
    pythonVersion:Â 3.10.12